# TABLAS DE DETALLES PARA CLIENTE Y VENDEDOR
def detalles(code, salesman, marca_bici, cantidad, bonificacion, bono, fecha, cc2, cliente, precio_bici, tipob, tamaño, color, subtotal, total_iva, precio_total):
  print('|                          DETALLE VENDEDOR                    |')
  print('|______________________________________________________________|')
  print('| CÓDIGO |NOMBRE VENDEDOR| MARCA | CANTIDAD | COMISION   |')
  print('|--------------------------------------------------------------|')
  print(f'|{code}| {salesman}    |  {marca_bici} |    {cantidad}     | {bonificacion:,}  {bono}|')
  print('|______________________________________________________________|')
  print(f'|Fecha: {fecha}|')
  print(' ==============================================================')

  print(' ==============================================================')
  print('|                          DETALLE CLIENTE                   |')
  print('|______________________________________________________________|')
  print('| IDENTIFICACIÓN|     NOMBRE    |       MARKET CICLE S.A       |')
  print('|---------------|---------------|------------------------------|')
  print(f'|   {cc2}  |   {cliente}  |          *****             |')
  print('|---------------|---------------|------------------------------|')
  print('| MARCA |   TIPO   | VALOR UNIDAD | CANTIDAD  |TALLA|  COLOR   |')
  print('|--------------------------------------------------------------|')
  print(f'| {marca_bici}  |  {tipob}  |  {precio_bici:,}   |       {cantidad}     | {tamaño} | {color}|')
  print('|______________________________________________________________|')
  print('|    SUBTOTAL    |    VALOR IVA    |     TOTAL A PAGAR         |')
  print('|--------------------------------------------------------------|')
  print(f'|    {subtotal:,}   |    {total_iva:,.0f}      |      {precio_total:,.0f}            |')
  print('|--------------------------------------------------------------|')
  print(f'|Fecha: {fecha}                                             |')
  print('|==============================================================|')
  return ('')